### PR TITLE
Config

### PR DESCRIPTION
**Pull request by mjmottram**
Allow arbitrary number of axes, dimensions specified in config file.  Note that there will be compatibility issues with old spectra file (load_old will assist with this, but I've also removed all of the old timing dimensions).

### CODE REVIEW

**Comment by mjmottram** [comment]
Closes #58

**Comment by jwaterfield** [comment]
Hi @mjmottram  would you be able to fix the conflicts? I can take over the PR afterwards if you'd like?

**Comment by mjmottram** [comment]
Urgh, this is pretty horrible to fix having not really used Echidna before.

**Comment by jwaterfield** [comment]
Don't worry too much about getting it completely working, I can finish it off. I just need the conflicts resolved so I can checkout the branch

**Comment by mjmottram** [comment]
Done, I think.  Will need some tests run by someone.

**Comment by jwaterfield** [comment]
OK great I'll merge these commits into my branch and I'll work on checking that all the functionality is still there. Thanks!

**Pull request merged**
