### PR TITLE
Add spectra

### PR DESCRIPTION
**Pull request by jwaterfield**
Added add spectrum function to spectra and example script

### CODE REVIEW

**Comment by jwaterfield** [comment]
This has been linked to the readme pull request because that hasn't been merged yet. Need to merge #35 first. Tagging @EdLeming  so he can see how to combine hdf5 once the pull request goes through.

**Comment by jwaterfield** [comment]
Not sure I know what you mean? I have ran sphinx-apidoc and make html and commited all files in the above commit. Is there something missing?

**Comment by arushanova** [comment]
Its just in README it wasn't written to type "make html" in docs/ after running sphinx-apidoc.

**Comment by arushanova** [comment]
Also, I couldn't run Ed's scripts in the directory where they are currently stored. I had to do it in the main echidna directory (i.e. in echidna, rather then echidna/echidna or echidna/echidna/scripts). If everyone has the same issue, then it's worth pointing it out somewhere...

**Comment by EdLeming** [comment]
Yeah, unless we add an env.sh (including the below) to be sourced in the echidna directory before moving to the scripts directory, that will be a problem.

export PYTHONPATH=$PYTHONPATH:$(pwd)

**Comment by jwaterfield** [comment]
Is that what you meant @arushanova?

**Comment by arushanova** [comment]
Not quite. This is what I meant:
...
sphinx-apidoc -f -H echidna -o docs echidna/
cd docs
make html

**Comment by jwaterfield** [comment]
Done

**Comment by arushanova** [comment]
It should be also briefly explained how to use echidna and the examples can be found in scripts.

**Comment by jwaterfield** [comment]
Done

**Comment by arushanova** [comment]
I think it looks nice.

**Pull request merged**
