### PR TITLE
Shift 

### PR DESCRIPTION
**Pull request by jwaterfield**
Added a class which shifts the values of a spectra variable.
Requires #87 to be merged first.

### CODE REVIEW

**Comment by ashleyrback** [comment]
Failure on unittest:
```
======================================================================
FAIL: test_scale (test_scale.TestScale)
Tests the variable scaling method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ashley/snoplus/software/echidna/echidna-pr/echidna/test/test_scale.py", line 86, in test_scale
    % (expected_sigma, sigma))
AssertionError: Expected sigma 0.22, fitted sigma 0.22284080161

----------------------------------------------------------------------
```
I think you just missed the `import numpy` in `shift.py`.

**Comment by ashleyrback** [comment]
and one minor pep8 error:
```
echidna/test/test_shift.py:112:1: W391 blank line at end of file
```

**Comment by ashleyrback** [comment]
Other than those two, looks good to merge!

**Comment by jwaterfield** [comment]
@ashleyrback Should be good to go now.

**Comment by ashleyrback** [comment]
Happy, merging!

**Pull request merged**
