### PR TITLE
Added a try and except

### PR DESCRIPTION
**Pull request by jwaterfield**
Fixed bug for when energies or radius are out of bounds when smeared

### CODE REVIEW

**Comment by jwaterfield** [comment]
Only if they outside the range of the bins in the histogram. Good point though, how are we keeping track of number of raw events in the spectra? The number events successfully filled is the important number that should be recorded not the total events in the root file/ntuple.

**Comment by ashleyrback** [comment]
Actually yes this does make sense, as the smearing simulates reconstructing the energy/position, so all this is saying is that at this energy/position resolution, we may have some events that could not be re-constructed within the 10 m radius, which we would not want to include in the analysis anyway, so the events shouldn't be added to the spectrum. The number of events contained in the spectrum is always given by `Spectra.sum()`, but this will change depending on scaling. `Spectra._num_decays` always tells you how many decays the spectrum represents, again this changes when the spectrum is scaled.

**Comment by jwaterfield** [comment]
Should we record Spectra.sum() as a variable in the spectra object called something like Spectra._raw_events before it is scaled so this information isn't lost once the scaling happens?

**Comment by ashleyrback** [comment]
Maybe, what would actually need to use it for, just knowing how many events were actually filled to `Spectra`? I guess you'd have to create `Spectra._raw_events` when `Spectra` is initialised and then update it with the fill weight every time `Spectra.fill` is called.

**Comment by jwaterfield** [comment]
You would need to keep track of your statistics. E.g. how many times more events are in your spectra then what is expected in x number years of running. _raw_events would need to be incremented by 1 each time you filled as well not by weight so the number stored is the true number of events used to construct your spectra

**Comment by ashleyrback** [comment]
Yeah I guess that would be better, as long as each call of the `fill` method only represents one raw event, because you could technically add multiple events to a single energy, radius, time bin, by specifying a weight as an integer greater than 1 - a bit like the `SetBinContent` method in ROOT. I think this should be opened up as a separate issue.

**Comment by ashleyrback** [comment]
Anyway this pull request is fine now. I've tested it with my `dump_smeared` script from #29 as well. Merging!

**Pull request merged**
