### PR TITLE
Tidied up dump_spectra_ntuple.py and dump_spectra_root.py and added mult...

### PR DESCRIPTION
**Pull request by EdLeming**
...i_ntuple_spectrum.py

### CODE REVIEW

**Comment by EdLeming** [comment]
Ok, that should be done.

**Comment by ashleyrback** [comment]
@EdLeming it's not showing that you've added any new commits. Could you just check that you've pushed to `snoplusuk_test_scripts`, cheers.

**Comment by EdLeming** [comment]
It's showing now

**Comment by arushanova** [comment]
Just to clarify this supersedes #20

**Comment by arushanova** [comment]
Merging

**Pull request merged**
