### PR TITLE
first pass at setting cut parameters at runtime

### PR DESCRIPTION
**Pull request by mjmottram**
I decided that I wanted to add some extra cuts (e.g. a simple evIndex==0) when extracting from a file, this isn't possible at the moment without first parsing through an ntuple to create a new one.  This PR allows for users to specify their own cuts and also removes lots of repeated code from dsextract. That said, it sounds like people don't really like dsextract anyway so maybe it should be scrapped and people write their own scripts to run in a manner of their choosing.

I also updated the num_decays for ntuples to remove duplicated MC events.

### CODE REVIEW

**Comment by arushanova** [comment]
As expected, I agree with this statement "That said, it sounds like people don't really like dsextract anyway so maybe it should be scrapped and people write their own scripts to run in a manner of their choosing."  For my studies I can't use existing extractors and it is much easier for me to simply create hdf5 file in the end of my code. But, I can write extractors, when I have time, if needed. 

When you say "people", I'm not sure whom you are talking about. It seems, that Ashley and James are both using this method and, I suppose, find it useful.

**Comment by mjmottram** [comment]
Ah, but that's how this might help.  You can now pass arbitrary lists of cuts (e.g. on classifier values) to the `dsextract` module classes.  I know Ashley wasn't sure whether `dsextract` should remain in the codebase.  Personally I think it's useful purely to ensure consistency when keeping track of total events before cuts are applied.

**Comment by ashleyrback** [comment]
@mjmottram you'll need to merge in from snoplusuk/master to resolve the conflicts.

**Comment by ashleyrback** [comment]
@snoplusuk/core any volunteers to review this?

**Comment by mjmottram** [comment]
Conflicts fixed.

**Comment by mjmottram** [comment]
As a comment, the conflicts were mainly caused by stylistic changes in the fit_class PR that were unrelated to the feature being developed on that branch, it's better to keep these changes separate to reduce conflicts for other developers.

**Pull request closed without merging**
