### PR TITLE
Temporary bug fix for decay weights

### PR DESCRIPTION
**Pull request by jwaterfield**
The decay weights are effecting how the spectra is being scaled. This is a temporary fix assuming you use 10 bins of time. This relates to issue #28 and must be resolved correctly.

### CODE REVIEW

**Comment by ashleyrback** [comment]
@jwaterfield looks fine, could you just add a short sentence to the docs to say that the weights are currently disabled, preferably in **bold** or something to stand out, cheers.

**Comment by ashleyrback** [comment]
The same sentence in each function.

**Comment by jwaterfield** [comment]
Done

**Comment by ashleyrback** [comment]
@jwaterfield, good apart from the typo

**Comment by jwaterfield** [comment]
Fixed

**Comment by ashleyrback** [comment]
Merging

**Pull request merged**
